# -*- coding: utf-8 -*-
"""Recommendation System - SegarBox

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1myr2koQgK_p2IXeSr3ovLQEw5lnHlEH5
"""

#Importing libraries
#Product popularity based recommendation system targeted at new customers

import numpy as np
import pandas as pd
import sklearn
from sklearn.decomposition import TruncatedSVD
import matplotlib.pyplot as plt

#Style used for Matplotlib data insight
plt.style.use("ggplot")

#Loading the dataset

url = 'https://raw.githubusercontent.com/SegarBox/Recommendation-System/main/ratings_Beauty_2.csv'
segarbox_ratings = pd.read_csv(url)
segarbox_ratings = segarbox_ratings.dropna()
segarbox_ratings.head()

popular_products = pd.DataFrame(segarbox_ratings.groupby('ProductId')['Rating'].count())
most_popular = popular_products.sort_values('Rating', ascending=False)
most_popular.head(10)

most_popular.head(10).plot(kind = "bar")

#Model-based collaborative filtering system
#Recommend items to users based on purchase hsitory and similarity of ratings provided by other users who bought same items

#Subset of product ratings
#Filled unknown values(empty) with 0

segarbox_subset = segarbox_ratings.head(10000)
ratings_utility_matrix = segarbox_subset.pivot_table(values='Rating', index='UserId', columns='ProductId', fill_value=0)
ratings_utility_matrix.head()

#Transposing the matrix

X = ratings_utility_matrix.T
X.head()

#Decomposing the Matrix

SVD = TruncatedSVD(n_components=10)
decomposed_matrix = SVD.fit_transform(X)

#Defined correlation matrix

correlation_matrix = np.corrcoef(decomposed_matrix)

#Code Testing
#Input number of Customer

num = int(input("Enter number of Customer :"))
i = X.index[num]
print("Product ID :", i) 

product_names = list(X.index)
product_ID = product_names.index(i)

#Correlation for all items with the item purchased based on items rated by other customers who bought the same product

correlation_product_ID = correlation_matrix[product_ID]

#Top 10 highly correlated products in sequence

Recommend = list(X.index[correlation_product_ID > 0.90])

# Removes the item already bought by the customer
Recommend.remove(i) 
Recommend_system = Recommend[0:9]

if len(Recommend_system) <= 10:
    print('Less Data')
else:
    print(Recommend_system)

