name: Flask Pipline

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: "remote server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SSH }}
          username: ${{ secrets.USERNAME_SSH }}
          password: ${{ secrets.PASSWORD_SSH }}
          script: |
            cd /home/widi/stacks/Recommendation-System
            git pull origin main
